services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"

  chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cassandra
    ports:
      - "12345:12345"
    environment:
      CASSANDRA_CONTACT_POINTS: cassandra
      CASSANDRA_PORT: 9042
    # command: tail -f /dev/null  # keep the container running
    # restart: always
