services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh cassandra 9042 -e 'describe keyspaces'"]
      interval: 30s
      timeout: 20s
      retries: 10

  chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "12345:12345"
    environment:
      CASSANDRA_CONTACT_POINTS: cassandra
      CASSANDRA_PORT: 9042
    restart: unless-stopped
