Secure Chat: common/include/protocol.h File Reference
protocol.h File Reference
#include <stdint.h>
Data Structures
struct packet_t
Macros
#define LOGIN 1
#define MESSAGE 2
#define PRIVATE_MESSAGE 3
#define LOGOUT 4
#define ERROR 5
#define PORT 12345
#define BUFFER_SIZE 1024
Functions
const unsigned char * get_hash (const char *password)
const char * get_timestamp ()
const char * generate_unique_user_id (const char *username)
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 1024
Definition at line 13 of file protocol.h.
Referenced by generate_unique_user_id(), handle_client(), receive_messages(), run_client(), and run_server().
ERROR
#define ERROR 5
Definition at line 10 of file protocol.h.
LOGIN
#define LOGIN 1
Definition at line 6 of file protocol.h.
LOGOUT
#define LOGOUT 4
Definition at line 9 of file protocol.h.
MESSAGE
#define MESSAGE 2
Definition at line 7 of file protocol.h.
PORT
#define PORT 12345
Definition at line 12 of file protocol.h.
Referenced by run_client(), and run_server().
PRIVATE_MESSAGE
#define PRIVATE_MESSAGE 3
Definition at line 8 of file protocol.h.
Function Documentation
generate_unique_user_id()
const char * generate_unique_user_id (const char * username)
Definition at line 27 of file protocol.c.
{
    char input_str[BUFFER_SIZE];
    snprintf(input_str, BUFFER_SIZE, "%s%s", username, get_timestamp());
    const unsigned char *hash = get_hash(input_str);
    static char user_id[65];
    for(int i = 0; i < 32; ++i)
    {
        snprintf(user_id + (i * 2), 3, "%02x", hash[i]);
    }
    user_id[64] = '\0';
    return user_id;
}
References BUFFER_SIZE, get_hash(), and get_timestamp().
get_hash()
const unsigned char * get_hash (const char * password)
Definition at line 12 of file protocol.c.
{
    unsigned char* hash = (unsigned char*)malloc(EVP_MAX_MD_SIZE);
    EVP_Digest(password, sizeof(password), hash, NULL, EVP_sha256(), NULL);
    return hash;
}
Referenced by generate_unique_user_id().
get_timestamp()
const char * get_timestamp ()
Definition at line 19 of file protocol.c.
{
    static char timestamp_str[20];
    time_t now = time(NULL);
    strftime(timestamp_str, sizeof(timestamp_str), "%Y%m%d%H%M%S", localtime(&now));
    return timestamp_str;
}
Referenced by generate_unique_user_id().