name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make common
      run: cd common && make
    
    - name: Make server
      run: cd server && make

    - name: Make client
      run: cd client && make
